### ISSUE TITLE
suggestion: put the initial prompt into the config

### ISSUE THREAD

**Issue by kamil-malinski** [Leask/halbot#11]
Hi!

I would like to suggest a new feature: put the initial prompt (the one that initiates "Sydney") into the config-file, so one can customize it, e.g. with the language I would like to get replies in.

Kamil

**Comment by Leask** [comment]
Good idea! I will do so. Thanks!

**Comment by Leask** [comment]
I have a bigger plan to tweak the whole prompt system. This will happen with the big update coming.

**Comment by Leask** [comment]
@kamil-malinski The latest version supports session storage and lots of settings. So the foundation to support the initial prompt is ready. I will add this feature soon.

**Comment by kamil-malinski** [comment]
> @kamil-malinski The latest version supports session storage and lots of settings. So the foundation to support the initial prompt is ready. I will add this feature soon.

fantastic news, thanks a lot!

**Comment by Leask** [comment]
You can now config the initial prompt by the `hello` field in the config file. And you can use `/set --hello="bonjour"` to set the initial prompt in every chat session. Any problem, please let me know.
