### ISSUE TITLE
suggestion: add selected suggestion to reply

### ISSUE THREAD

**Issue by kamil-malinski** [Leask/halbot#12]
Hi!

Thanks for adding the clickable suggested reply buttons, they work great!

I would like to suggest something related to them: when selecting a suggested reply, put the selected reply at the top of the bots reply so one can see what was sent to the bot. This would make it easier to get the context of the reply when going through older conversations.

So it looks like this:

[Sydneys Reply]
[Suggested Reply 1][Suggested Reply 2][Suggested Reply 3]

[Selected Suggested Reply 2]
[Sydneys Reply]
[Suggested Reply 1][Suggested Reply 2][Suggested Reply 3]

In this example I selected "Suggested Reply 2" and therefore it is displayed before Sydneys second reply.

Kamil

**Comment by Leask** [comment]
☑️ Feature accepted 😄

**Comment by Leask** [comment]
Done

<img width="861" alt="Screenshot 2023-03-27 at 9 24 11 PM" src="https://user-images.githubusercontent.com/233022/228102581-1a44cfc8-3462-4eb1-881a-cbd9bed9e4cc.png">

🍻

PS: the latest version has a lot of changes under the hood. Some things may act unstable for 1 or 2 minor versions. I have tried my best to make it work. At least It works smoothly for me now. 😄
