### ISSUE TITLE
How to get bing user token

### ISSUE THREAD

**Issue by Am1nCmd** [Leask/halbot#13]
Hi there, I'm curious how to get a bing user token from cookies.

I already have access to bing chat but didn't know how to obtain the token.

**Comment by Leask** [comment]
<img width="1270" alt="Screenshot 2023-03-28 at 7 10 07 PM" src="https://user-images.githubusercontent.com/233022/228387168-2d13a857-4e68-4f8d-b938-e4d046ecfe5a.png">

This is how you get your bing user token.

**Comment by rmay1er** [comment]
<img width="958" alt="Снимок экрана 2023-12-11 в 16 14 34" src="https://github.com/Leask/halbot/assets/11348902/81fc5f09-e41a-43b9-849b-4db378f34084">
When i ask /bing hello test

he said null

i tried to update _U cookie in .halbot.json it doesn't help

**Comment by Leask** [comment]
We have closed and no longer support Bing. Sorry.
