### ISSUE TITLE
are options global?

### ISSUE THREAD

**Issue by kamil-malinski** [Leask/halbot#21]
Hello!

 I must say, you have made remarkable progress with this project in such a short time! 👍 

I have a query regarding the new options. Are they global, i.e. applicable for every user? Or does each user have their own set of options? For instance, if I set a new prompt for myself, will every other user see this new prompt or only I will be able to see it?

 Best regards

Kamil

**Comment by Leask** [comment]
Thanks!

The options in the config file are global, and the options you set in the chats are only for the current chat tab.

If you are in a private chat, you can consider that the options are your personal preference.

But if you run the `set` command in the group chat tabs, that means you config the bot's behaviour for the group.

:)
