### ISSUE TITLE
Suggest:Add access_token type to use chatgpt,and this is the most easy way to use gpt4 for plus user.

### ISSUE THREAD

**Issue by iknow2333** [Leask/halbot#25]
So we don't have to keep the web open until gpt4 completes his answer slowly.

**Comment by Leask** [comment]
How, can you show me more info? thanks!

**Comment by iknow2333** [comment]
Thanks for your response!

I am sorry I am not professional that may give you something wrong.

Does this program base on node-chatbot-API?
If so, here is the demo.
https://github.com/waylaidwanderer/node-chatgpt-api/blob/main/demos/use-browser-client.js
and maybe can change the model here:
https://github.com/waylaidwanderer/node-chatgpt-api/blob/main/src/ChatGPTBrowserClient.js
get accessToken here:
https://chat.openai.com/api/auth/session

This program seems to work well in the same way. I can add an env variable "OPENAI_API_MODEL=gpt4" to use gpt4.
https://github.com/Chanzhaoyu/chatgpt-web

**Comment by iknow2333** [comment]
Ignore it, access_token doesn't seem to work stably

**Comment by Leask** [comment]
Yes, the web client API is not so stable for now.
Thanks for your idea. I will keep an eye on model v4.

**Comment by iknow2333** [comment]
> Yes, the web client API is not so stable for now.
> Thanks for your idea. I will keep an eye on model v4.

https://github.com/linweiyuan/go-chatgpt-api
这个仓库已经成功绕过cf了，而且比之前的社区代理更加快速和安全，所有我们要做的仅仅是部署在私有服务器上

**Comment by Leask** [comment]
不錯，我看看是不是有可以借鑑的地方。🙏

**Comment by Leask** [comment]
https://github.com/linweiyuan/go-chatgpt-api 這個已經不可用了。感謝推薦。關閉。
