### ISSUE TITLE
建议的回复不能正常工作

### ISSUE THREAD

**Issue by iknow2333** [Leask/halbot#26]
![29A2DC57-2BB8-44B3-857D-E6504D1A9269](https://user-images.githubusercontent.com/103983460/232363953-9c0ddee4-3e61-441c-b627-b3726288cd11.jpeg)
![917FF210-AF09-4CEE-9D54-0BF65446EA44](https://user-images.githubusercontent.com/103983460/232363961-c0b42c89-52c2-490f-9807-1e7803472a1a.jpeg)
这个问题很容易发生，而且通常发生在👀出现后，我确定我没有达到最大对话次数。
稳定的触发方法：提出一些较复杂的问题然后叫她深入
![66B74CFB-7885-41E7-8D60-C510C09495CB](https://user-images.githubusercontent.com/103983460/232364831-ee2df115-9995-4435-ae19-7faec7945c1a.jpeg)

**Comment by Leask** [comment]
這是一個 上游 api 的錯誤，https://github.com/waylaidwanderer/node-chatgpt-api/issues/288 。
目前bing沒有正式的api，用的是webtoken的方法，穩定性的確不好，推薦使用ChatGPT，它有官方API，穩定性和速度都好很多。我會關注這個問題，有進展會在這裡更新。

**Comment by Leask** [comment]
對 bing 的支持將會慢慢淡出，未來的版本將會全面轉向 chatgpt 原生api，故，計畫關閉這一類的issue。
