### ISSUE TITLE
Issue: Duplicate answer even with different question

### ISSUE THREAD

**Issue by Am1nCmd** [Leask/halbot#27]
Hi, I found another issue

I ask 2 different questions, bot answers with the similar duplicate answer
<img width="514" alt="image" src="https://user-images.githubusercontent.com/15339573/233423725-53d06bc5-7efe-4c79-bfc0-9fd1f358d7aa.png">

**Comment by Leask** [comment]
Thanks! The Bing engine is not stable enough. I will tweak it in the coming updates.

**Comment by Leask** [comment]
Close issues related to Bing engine.
