### ISSUE TITLE
发送request到telegram api 超时			

### ISSUE THREAD

**Issue by LukyBruce** [Leask/halbot#3]
发送request到telegram api 超时			

reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: request to https://api.telegram.org/bot12345:[REDACTED]/getMe failed, reason: connect ETIMEDOUT 199.59.149.236:443
    at ClientRequest.<anonymous> (/Users/rongjinzhou/robots1/halbot/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:512:28)
    at TLSSocket.socketErrorListener (node:_http_client:496:9)
    at TLSSocket.emit (node:events:512:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

**Comment by Leask** [comment]
你的網絡 ping 199.59.149.236 把輸出帖一下？謝謝。

**Comment by LukyBruce** [comment]
我的telegram是可以用的为啥 ping不通？
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

**Comment by Leask** [comment]
你在國內還是國外？

**Comment by LukyBruce** [comment]
国内

**Comment by Leask** [comment]
你的 telegram 是翻牆訪問的麼？

**Comment by LukyBruce** [comment]
是的， 我shell里面也设置代理了 还是ping不通

**Comment by LukyBruce** [comment]
我另外一个bot 可以用。

**Comment by Leask** [comment]
node 代碼應該不會直接讀取到代理，你如何配置的代理？我可以考慮支持一下代理服務器。

**Comment by LukyBruce** [comment]
有路由器上面 shellclash, 也有local clash 的client

**Comment by LukyBruce** [comment]
我怀疑node里面没能读取代理。

**Comment by Leask** [comment]
理論上應該就是不讀取的，我現在在國外，的確沒有考慮這些問題。我考慮一下吧，這個issue先保持開啟狀態。

**Comment by LukyBruce** [comment]
ok, 多谢。

**Comment by Leask** [comment]
不客氣😇

**Comment by LukyBruce** [comment]
应该是 proxy 的问题了 我怀疑node 默认不会读取system proxy， 我用router上面的clash 就好了

**Comment by Leask** [comment]
代理的問題，這裡就不處理了，🙏感謝！
