### ISSUE TITLE
should be only one telegram bot instance running

### ISSUE THREAD

**Issue by xnetsc** [Leask/halbot#31]
as the title
![image](https://github.com/Leask/halbot/assets/18025276/cd8f7128-3589-44e5-ab19-e6a695592810)

**Comment by Leask** [comment]
This is an API error `only triggered by the telegram server`, meaning your bot token is used in another bot, maybe Hotbot or another bot program. Check your token first. If you are not sure, please create another bot token.

**Comment by xnetsc** [comment]
> This is an API error `only triggered by the telegram server`, meaning your bot token is used in another bot, maybe Hotbot or another bot program. Check your token first. If you are not sure, please create another bot token.

no,i have fixed the issue by 
```
if(process.bot) return process.bot;



process.bot=bot
```

the old code may call init multiply times.

**Comment by Leask** [comment]
That does not make any sense.

**Comment by xnetsc** [comment]
> That does not make any sense.

the issue is a bug,not as you said "use bot at other place".
it's caused by call "init" multiply times

**Comment by Leask** [comment]
You should only initiate one time for a bot. And using `process.bot` is a bad idea for this "fix". You can keep your own version, but I am not going to follow. Sorry.

**Comment by xnetsc** [comment]
> You should only initiate one time for a bot. And using `process.bot` is a bad idea for this "fix". You can keep your own version, but I am not going to follow. Sorry.

the init called many times in utilitas/lib/bot.js.

it should be fixed by some way

**Comment by Leask** [comment]
Could you tell me how you initiated the bot multiple times?

**Comment by xnetsc** [comment]
> Could you tell me how you initiated the bot multiple times?

![image](https://github.com/Leask/halbot/assets/18025276/a9ebb682-7098-4e5a-8a98-5149ef488d16)

![image](https://github.com/Leask/halbot/assets/18025276/ecf61476-49e1-4483-a27b-40d237f907df)

**Comment by Leask** [comment]
No, init func will not create a new instance. It will get the instance one instead because these two lines call the init func without options: https://github.com/Leask/utilitas/blob/master/lib/bot.mjs#LL680C5-L680C5

**Comment by Leask** [comment]
`Init` means `get` or `init`.

**Comment by xnetsc** [comment]
> `Init` means `get` or `init`.

but after i add **THE CODE**,the issue is fixed

**Comment by Leask** [comment]
There should be another issue hidden. We run more than ten different instances. You are the first one facing this. This func is stable enough.

**Comment by Leask** [comment]
Try removing your `fix` and creating a new token. If you can reproduce this issue, please let me know.

**Comment by xnetsc** [comment]
![image](https://github.com/Leask/halbot/assets/18025276/9ae0cf00-8d15-440e-8dab-5336b58ebf89)
![image](https://github.com/Leask/halbot/assets/18025276/72d88673-8c2b-47f7-9119-f729c3903f4b)

after this,all error disapeared.


from this point, there are definitely cases where init is called repeatedly.

**Comment by xnetsc** [comment]
> Try removing your `fix` and creating a new token. If you can reproduce this issue, please let me know.

the token is newly created for the deploy,no any one else know it.

**Comment by Leask** [comment]
I cloned your branch removed this fix, and can not reproduce this issue. 🤔️ Please just let me reproduce it.

**Comment by xnetsc** [comment]
you can deploy it without the fix to railway for test

**Comment by xnetsc** [comment]
> I cloned your branch removed this fix, and can not reproduce this issue. 🤔️ Please just let me reproduce it.

i have modified the dependency to my fixed version in package.json

maybe you are still using my version
