### ISSUE TITLE
[ERR_ASSERTION]: Say API is not available.

### ISSUE THREAD

**Issue by kamil-malinski** [Leask/halbot#38]
Hi!

When I start the bot I get:

```console
[HALBOT] AssertionError [ERR_ASSERTION]: Say API is not available.
```

What is the Say API and how do I install it?

**Comment by Leask** [comment]
Hi, 

Are you using Bing hacking API?
Because Bing API does not support TTS, please disable the TTS feature for now.
And one more thing: I am fading out the Bing web-hacking support. Sorry about that.
