### ISSUE TITLE
make suggested responses clickable

### ISSUE THREAD

**Issue by kamil-malinski** [Leask/halbot#7]
Hi!

Whenever the bot replies it suggest 3 responses, e.g.
```
Suggested responses:
1. Was hast du morgen vor?
2. Wie kannst du mir helfen?
3. Bist du wirklich ein AI-Assistent?
```

Is it possible to make this suggestions clickable? I saw that https://github.com/pininkara/BingChatBot has clickable suggestions and wonder if they could be implemented in halbot too.

Kamil

**Comment by elliclee** [comment]
This feature looks good and practical. I hope it can be added too.

**Comment by elliclee** [comment]
Or the suggested responses can be Closed.

**Comment by elliclee** [comment]
It would be better if the '🤖 Bing' can be removed or can be changed to 'Sydney:', cause in the  Sydney mode, the AI name is Sydney~ 

![5](https://user-images.githubusercontent.com/1717254/227509155-b4d7eea8-ea80-4cf9-89b0-b33648b418b1.png)

**Comment by Leask** [comment]
<img width="967" alt="Screenshot 2023-03-27 at 1 44 49 PM" src="https://user-images.githubusercontent.com/233022/228023644-4dd2d006-9e31-4907-9d7d-751b7a24abea.png">

@kamil-malinski @elliclee: Clickable suggested responses have been supported!

@kamil-malinski But I don't want to replace `bing` with `Sydney` right now. There are many reasons. For example, using the `/` command to select between bots will be more difficult. And Sydney is just one of the personalities of `bing`. Maybe in the coming version, there will be more personalities that need support.  So this will be on hold, And thanks for your advice. I will keep an eye on it.
